# Generated by Django 4.0.3 on 2022-04-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='Services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='guest.services'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Remark',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='Status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
