# Generated by Django 4.0.3 on 2022-04-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_rename_services_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='RemarkDate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Waiting',
            field=models.BooleanField(default=False),
        ),
    ]
