# Generated by Django 4.0.3 on 2022-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0004_remove_appointment_remarkdate_appointment_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='company_name',
            field=models.CharField(default='Beauty Parlour', max_length=120),
        ),
    ]
