# Generated by Django 4.0.3 on 2022-04-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_pagedescription_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Gender',
        ),
    ]
