# Generated by Django 4.0.3 on 2022-04-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_remove_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PhoneNumber',
            field=models.CharField(max_length=15),
        ),
    ]
