# Generated by Django 4.0.3 on 2022-04-07 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guest', '0007_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Name',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
